apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: gateway
spec:
  api:
    serverUrl: http://acme-fitness.spring.animalrescue.online
    title: "ACME Fitness Gateway"
    description: "ACME Fitness application for Spring Cloud Gateway commercial product demos."
    documentation: "https://github.com/spring-cloud-services-samples/acme_fitness_demo/"
    version: "1.0.0-K8s"
    cors:
      allowedOrigins:
      - "http://api-portal.spring.animalrescue.online"
  metrics:
    wavefront:
      secret: wavefront-secret
      source: acme-fitness
  tracing:
    wavefront:
      secret: wavefront-secret
      source: acme-fitness
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scg-ingress
spec:
  rules:
  - host: acme-fitness.spring.animalrescue.online
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gateway
            port:
              number: 80
# Use v1beta1 Ingress if v1 is not available on your cluster
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: scg-ingress
# spec:
#   rules:
#     - host: acme-fitness.spring.animalrescue.online
#       http:
#         paths:
#           - backend:
#               serviceName: gateway
#               servicePort: 80
