apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: wavefrontproxy.gtt.tanzu.vmware.com.0.0.14
spec:
  refName: wavefrontproxy.gtt.tanzu.vmware.com
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/gtt/packages/wavefrontproxy:0.0.14
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        wavefront_svc_port:
          type: integer
          description: Port number for the service.
          default: 2878
        namespace:
          type: string
          description: Namespace to deploy into.
          default: wavefront-proxy
        wavefront_secret_name:
          type: string
          description: Secret in which the api token and url are stored. Specify the keys as well!
          default: wavefront-secret
        wavefront_uri_key:
          type: string
          description: Name of the key for the URI secret
          default: wavefront.uri
        wavefront_api_token_key:
          type: string
          description: Name of the key for the API token
          default: wavefront.api-token
  version: 0.0.14
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: wavefrontproxy.gtt.tanzu.vmware.com
spec:
  displayName: wavefrontproxy
  longDescription: wavefrontproxy.gtt.tanzu.vmware.com
  shortDescription: wavefrontproxy.gtt.tanzu.vmware.com
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  name: wavefrontproxy
spec:
  packageRef:
    refName: wavefrontproxy.gtt.tanzu.vmware.com
    versionSelection:
      constraints: 0.0.14
  serviceAccountName: wavefrontproxy-sa
