apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: wavefrontproxy.gtt.tanzu.vmware.com
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - wavefront-proxy-package-contents/config
          - kbld: {}
      export:
      - imgpkgBundle:
          image: projects.registry.vmware.com/gtt/packages/wavefrontproxy
          useKbldImagesLock: true
        includePaths:
        - wavefront-proxy-package-contents/config
