apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: petclinic.gtt.tanzu.vmware.com
spec:
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - petclinic-package-contents/config
          - kbld: {}
      export:
      - includePaths:
        - petclinic-package-contents/config
