#@ load("@ytt:data", "data")  # for reading data values (generated via ytt's data-values-schema-inspect mode).
#@ load("@ytt:yaml", "yaml")  # for dynamically decoding the output of ytt's data-values-schema-inspect
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: #@ "wavefrontproxy.gtt.tanzu.vmware.com." + data.values.version
spec:
  refName: wavefrontproxy.gtt.tanzu.vmware.com
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: #@ "projects.registry.vmware.com/gtt/packages/wavefrontproxy:" + data.values.version
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
  valuesSchema:
    openAPIv3: #@ yaml.decode(data.values.openapi)["components"]["schemas"]["dataValues"]
  version: #@ data.values.version

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: wavefrontproxy.gtt.tanzu.vmware.com
spec:
  displayName: wavefrontproxy
  longDescription: wavefrontproxy.gtt.tanzu.vmware.com
  shortDescription: wavefrontproxy.gtt.tanzu.vmware.com

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  name: wavefrontproxy
spec:
  packageRef:
    refName: wavefrontproxy.gtt.tanzu.vmware.com
    versionSelection:
      constraints: #@ data.values.version
  serviceAccountName: wavefrontproxy-sa
