apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  name: wavefrontproxy.gtt.tanzu.vmware.com
spec:
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - wavefront-proxy-package-contents/config
          - kbld: {}
      export:
       - imgpkgBundle:
           image: projects.registry.vmware.com/gtt/packages/wavefrontproxy
           useKbldImagesLock: true
         includePaths:
          - wavefront-proxy-package-contents/config
